# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Akaramanapp < Formula
  desc ""
  homepage "https://github.com/akaramanapp/dev-tools"
  version "0.8"

  on_macos do
    url "https://github.com/akaramanapp/dev-tools/releases/download/v0.8/dev-tools_0.8_darwin_all.tar.gz"
    sha256 "73ce5678913f5abd5406a7e4d417821425c964033caeb6f7d84065914f0e6554"

    def install
      bin.install "dev-tools"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akaramanapp/dev-tools/releases/download/v0.8/dev-tools_0.8_linux_arm64.tar.gz"
      sha256 "8a4953ba9c17a598158a46d57979923bbd7ec4c445def65d2210b44edfeb4d38"

      def install
        bin.install "akaramanapp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akaramanapp/dev-tools/releases/download/v0.8/dev-tools_0.8_linux_amd64.tar.gz"
      sha256 "1bd1a84bf7fcfe3804042ea549e0fe89c2dd9cac9f39c6197963d026dda01c6c"

      def install
        bin.install "akaramanapp"
      end
    end
  end
end
